CREATE DATABASE QL_CuaHangPhanMem
GO

USE QL_CuaHangPhanMem
GO

CREATE TABLE TAIKHOAN
(
	MATK VARCHAR(100) NOT NULL,
	TENTK NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	CCCD VARCHAR(15),
	EMAIL VARCHAR(100) NOT NULL,
	SDT VARCHAR(15),
	DIACHI VARCHAR(200),
	SODU INT,
	HINHDAIDIEN TEXT,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MATK)
);

CREATE TABLE TAIKHOAN_QUANTRI
(
	TENTK NVARCHAR(50) NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_TAIKHOAN_QUANTRI PRIMARY KEY (TENTK)
);

CREATE TABLE NHAPHATHANH
(
	MANPH INT IDENTITY(1,1) NOT NULL,
	TENNPH NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_NHAPHATHANH PRIMARY KEY (MANPH),
);

CREATE TABLE LOAIPHANMEM
(
	MALOAI INT IDENTITY(1,1) NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAIPHANMEM PRIMARY KEY (MALOAI)
);

CREATE TABLE PHANMEM
(
	MAPM INT IDENTITY(1,1) NOT NULL,
	TENPM NVARCHAR(300) NOT NULL,
	MOTA NVARCHAR(1000),
	MANPH INT NOT NULL,
	NGAYPHATHANH DATE,
	THOIHAN INT NOT NULL,
	DONVITHOIHAN NVARCHAR(10) NOT NULL,
	DONGIA INT NOT NULL,
	SOLUONG INT NOT NULL,
	HINHANH TEXT,
	CONSTRAINT PK_PHANMEM PRIMARY KEY (MAPM),
	CONSTRAINT FK_PHANMEM_NHAPHATHANH FOREIGN KEY (MANPH) REFERENCES NHAPHATHANH(MANPH)
);

CREATE TABLE KEYPM
(
	MAPM INT NOT NULL,
	MAKEY INT IDENTITY(1,1) NOT NULL,
	GIATRI TEXT,
	TAIKHOAN TEXT,
	MATKHAU TEXT,
	CONSTRAINT PK_KEYPM PRIMARY KEY (MAPM, MAKEY),
	CONSTRAINT FK_KEYPM_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM)
);

CREATE TABLE THUOCLOAIPM
(
	MAPM INT NOT NULL,
	MALOAI INT NOT NULL,
	CONSTRAINT PK_THUOCLOAIPM PRIMARY KEY (MAPM, MALOAI),
	CONSTRAINT FK_THUOCLOAIPM_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM),
	CONSTRAINT FK_THUOCLOAIPM_LOAIPM FOREIGN KEY (MALOAI) REFERENCES LOAIPHANMEM(MALOAI)
);

CREATE TABLE HOADON
(
	MAHD VARCHAR(100) NOT NULL,
	MATK VARCHAR(100) NOT NULL,
	THOIGIANLAP DATETIME NOT NULL,
	TONGTIEN INT NOT NULL,
	TINHTRANG NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
	CONSTRAINT FK_HOADON_TAIKHOAN FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE CTHD
(
	MAHD VARCHAR(100) NOT NULL,
	MAPM INT NOT NULL,
	SOLUONG INT NOT NULL,
	THANHTIEN INT NOT NULL,
	CONSTRAINT PK_CTHD PRIMARY KEY (MAHD, MAPM),
	CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM)
);

CREATE TABLE CTHD_KEY
(
	MAHD VARCHAR(100) NOT NULL,
	MAPM INT NOT NULL,
	MAKEY INT NOT NULL,
	CONSTRAINT PK_CTHD_KEY PRIMARY KEY (MAHD, MAPM, MAKEY),
	CONSTRAINT FK_CTHD_KEY_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_KEY_KEYPM FOREIGN KEY (MAPM, MAKEY) REFERENCES KEYPM(MAPM, MAKEY)
);

CREATE TABLE THONGTINBOSUNG
(
	MAHD VARCHAR(100) NOT NULL,
	MAPM INT NOT NULL,
	STT INT NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	GIATRI TEXT NOT NULL,
	CONSTRAINT PK_THONGTINBOSUNG PRIMARY KEY (MAHD, MAPM, STT),
	CONSTRAINT FK_THONGTINBOSUNG_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_THONGTINBOSUNG_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM)
);

INSERT INTO NHAPHATHANH (TENNPH)
VALUES
    (N'Microsoft'),
    (N'Zoom Video Communications'),
    (N'Google'),
	(N'Design Science INC'),
	(N'Tonec FZE'),
	(N'Kaspersky Lab'),
	(N'ESET'),
	(N'VMware'),
	(N'Spotify'),
	(N'OpenAI'),
	(N'Electronic Arts Inc'),
	(N'Bandicam Company'),
	(N'Adobe');


INSERT INTO LOAIPHANMEM (TENLOAI)
VALUES
    (N'Văn phòng'),
    (N'Học tập'),
    (N'Giải trí'),
	(N'Game'),
	(N'Diệt virus');


set dateformat dmy
go

INSERT INTO PHANMEM (TENPM, MOTA, MANPH, NGAYPHATHANH, THOIHAN, DONVITHOIHAN, DONGIA, SOLUONG)
VALUES
    (N'Microsoft 365 Business Basic', N'Microsoft 365 Business Basic', 1, '09-2-2020', 1, N'Năm', 750000, 2),
    (N'Microsoft 365 Business Standard', N'Microsoft 365 Business Standard', 1, '09-2-2020', 1, N'Năm', 2850000, 2),
    (N'Microsoft 365 Business Premium', N'Microsoft 365 Business Premium', 1, '09-2-2020', 1, N'Năm', 5650000, 1),
    (N'Microsoft 365 Business Standard', N'Microsoft 365 Apps for Business', 1, '09-2-2020', 1, N'Năm', 2350000, 2),
    (N'Microsoft 365 Home', N'Microsoft 365 Home', 1, '09-2-2020', 1, N'Năm', 1550000, 5),
    (N'Microsoft 365 Personal', N'Microsoft 365 Personal', 1, '09-2-2020', 1, N'Năm', 1050000, 3),
    (N'Google Drive 100GB', N'Lưu trữ không giới hạn', 2, '27-07-2019', 3, N'Tháng', 20000, 2),
    (N'Youtube Primenum Personal', N'Giải trí không giới hạn', 3, '27-07-2006', 1, N'Tháng', 80000, 4),
    (N'Youtube Primenum Family', N'Giải trí không giới hạn', 3, '27-07-2006', 1, N'Tháng', 150000, 4),
    (N'Google Drive 200GB', N'Giải trí không giới hạn', 3, '27-07-2006', 1, N'Tháng', 35000, 4),
    (N'Google Drive 2TB', N'Giải trí không giới hạn', 3, '27-07-2006', 1, N'Tháng', 80000, 3),
    (N'Zoom Meeting', N'Học tập, làm việc mọi lúc', 2, '4-5-2018', 1, N'Năm', 3600000, 3),
    (N'Zoom Pro', N'Học tập, làm việc mọi lúc', 2, '4-5-2018', 1, N'Tháng', 300000, 3),
    (N'Mathtype', N'Phần mềm toán học', 4, '14-6-2016', 1, N'Năm', 1500000, 3),
    (N'Internet Download Manager', N'Tốc độ download nhanh nhất ', 5, '10-11-2012', 1, N'Năm', 230000, 6),
    (N'Kaspersky Internet Security 1PC', N'Bảo vệ bạn mọi lúc', 6, '19-1-2016', 1, N'Tháng', 300000, 3),
    (N'ESET Endpoint Security', N'Bảo vệ bạn mọi lúc', 7, '27-4-2014', 1, N'Tháng', 500000, 3),
    (N'VMware Workstation 17 Pro', N'Giả lập máy ảo', 8, '19-1-2016', 1, N'Năm', 5000000, 2),
    (N'VMware Workstation 17 Player', N'Giả lập máy ảo', 8, '12-3-2019', 1, N'Năm', 4000000, 1),
    (N'Spotify Premium', N'Nghe nhạc mọi lúc', 9, '17-9-2020', 1, N'Năm', 300000, 2),
    (N'Windows 11 Professional CD Key', N'Window', 1, '17-9-2020', 100, N'Năm', 5000000, 2),
    (N'Chat GPT Plus', N'Hỏi AI', 10, '17-9-2020', 6, N'Tháng', 600000, 2),
    (N'FIFA 23 (EA)', N'Fifa 23 Game', 11, '17-9-2020', 6, N'Tháng', 1200000, 1),
    (N'Bandicam', N'Quay màn hình', 12, '8-2-2016', 1, N'Năm', 1500000, 1),
    (N'Adobe Acrobat Pro 1PC', N'Adobe', 13, '19-3-2020', 100, N'Năm', 2000000, 1),
    (N'Windows 11 Education  CD Key', N'Window', 1, '17-9-2020', 100, N'Năm', 3000000, 2);

INSERT INTO THUOCLOAIPM(MAPM, MALOAI)
VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 1),
    (5, 1),
    (6, 1),
    (7, 1),
    (8, 3),
    (9, 3),
    (10, 1),
    (11, 1),
    (12, 1),
    (13, 1),
    (14, 2),
    (15, 1),
    (16, 5),
    (17, 5),
    (18, 2),
    (19, 2),
    (20, 3),
    (21, 1),
    (22, 2),
    (23, 4),
    (24, 1),
    (25, 2),
    (26, 1);