CREATE DATABASE QL_CuaHangPhanMem
GO

USE QL_CuaHangPhanMem
GO

CREATE TABLE TAIKHOAN
(
	MATK VARCHAR(100) NOT NULL,
	TENTK NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	CCCD VARCHAR(15),
	EMAIL VARCHAR(100) NOT NULL,
	SDT VARCHAR(15),
	DIACHI VARCHAR(200),
	SODU INT,
	HINHDAIDIEN TEXT,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MATK)
);

CREATE TABLE TAIKHOAN_QUANTRI
(
	TENTK NVARCHAR(50) NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_TAIKHOAN_QUANTRI PRIMARY KEY (TENTK)
);

CREATE TABLE NHAPHATHANH
(
	MANPH INT NOT NULL,
	TENNPH NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_NHAPHATHANH PRIMARY KEY (MANPH),
);

CREATE TABLE LOAIPHANMEM
(
	MALOAI INT NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAIPHANMEM PRIMARY KEY (MALOAI)
);

CREATE TABLE PHANMEM
(
	MAPM INT NOT NULL,
	TENPM NVARCHAR(300) NOT NULL,
	MOTA TEXT,
	MANPH INT NOT NULL,
	NGAYPHATHANH DATE,
	THOIHAN INT NOT NULL,
	DONVITHOIHAN NVARCHAR(10) NOT NULL,
	DONGIA INT NOT NULL,
	SOLUONG INT NOT NULL,
	HINHANH TEXT,
	CONSTRAINT PK_PHANMEM PRIMARY KEY (MAPM),
	CONSTRAINT FK_PHANMEM_NHAPHATHANH FOREIGN KEY (MANPH) REFERENCES NHAPHATHANH(MANPH)
);

CREATE TABLE KEYPM
(
	MAPM INT NOT NULL,
	MAKEY INT NOT NULL,
	GIATRI TEXT,
	TAIKHOAN TEXT,
	MATKHAU TEXT,
	CONSTRAINT PK_KEYPM PRIMARY KEY (MAKEY),
	CONSTRAINT FK_KEYPM_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM)
);

CREATE TABLE THUOCLOAIPM
(
	MAPM INT NOT NULL,
	MALOAI INT NOT NULL,
	CONSTRAINT PK_THUOCLOAIPM PRIMARY KEY (MAPM, MALOAI),
	CONSTRAINT FK_THUOCLOAIPM_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM),
	CONSTRAINT FK_THUOCLOAIPM_LOAIPM FOREIGN KEY (MALOAI) REFERENCES LOAIPHANMEM(MALOAI)
);

CREATE TABLE HOADON
(
	MAHD	 VARCHAR(100) NOT NULL,
	MATK VARCHAR(100) NOT NULL,
	THOIGIANLAP DATETIME NOT NULL,
	TONGTIEN INT NOT NULL,
	TINHTRANG NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
	CONSTRAINT FK_HOADON_TAIKHOAN FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE CTHD
(
	MAHD VARCHAR(100) NOT NULL,
	MAPM INT NOT NULL,
	SOLUONG INT NOT NULL,
	THANHTIEN INT NOT NULL,
	CONSTRAINT PK_CTHD PRIMARY KEY (MAHD, MAPM),
	CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM)
);

CREATE TABLE CTHD_KEY
(
	MAHD VARCHAR(100) NOT NULL,
	MAPM INT NOT NULL,
	MAKEY INT NOT NULL,
	CONSTRAINT PK_CTHD_KEY PRIMARY KEY (MAHD, MAPM, MAKEY),
	CONSTRAINT FK_CTHD_KEY_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_KEY_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM),
	CONSTRAINT FK_CTHD_KEY_KEYPM FOREIGN KEY (MAKEY) REFERENCES KEYPM(MAKEY)
);

CREATE TABLE THONGTINBOSUNG
(
	MAHD VARCHAR(100) NOT NULL,
	MAPM INT NOT NULL,
	STT INT NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	GIATRI TEXT NOT NULL,
	CONSTRAINT PK_THONGTINBOSUNG PRIMARY KEY (MAHD, MAPM, STT),
	CONSTRAINT FK_THONGTINBOSUNG_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_THONGTINBOSUNG_PHANMEM FOREIGN KEY (MAPM) REFERENCES PHANMEM(MAPM)
);